
import { ComplianceStatus, ChecklistItem } from './types';

export const G3022_DEFAULT_CHECKLIST: ChecklistItem[] = [
  { id: '5', name: '溫室氣體盤查邊界', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.1', name: '組織邊界', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.2', name: '報告邊界', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.2.1', name: '建立報告邊界', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.2.2', name: '直接溫室氣體排放與移除', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.2.3', name: '間接溫室氣體排放', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.2.4', name: '溫室氣體盤查', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6', name: '溫室氣體排放與移除之量化', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.1', name: '溫室氣體源與匯之鑑別', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.2', name: '量化方法之選擇', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.2.1', name: '一般', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.2.2', name: '使用於量化之數據選擇與蒐集', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.2.3', name: '溫室氣體量化模式之選擇或發展', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.3', name: '溫室氣體排放與移除之計算', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.4', name: '基準年之溫室氣體盤查', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.4.1', name: '基準年之選擇與建立', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '6.4.2', name: '基準年溫室氣體盤查之審查', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '7', name: '減緩活動', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '7.1', name: '溫室氣體排放減量與移除增量倡議', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '7.2', name: '溫室氣體排放減量與移除增量專案', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '7.3', name: '溫室氣體排放減量或移除增量目標', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '8', name: '溫室氣體盤查品質管理', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '8.1', name: '溫室氣體盤查資訊管理', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '8.2', name: '文件保留與紀錄保存', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '8.3', name: '評估不確定性', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '9', name: '溫室氣體報告', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '9.1', name: '一般', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '9.2', name: '規劃溫室氣體報告', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '9.3', name: '溫室氣體報告之內容', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '9.3.1', name: '要求之資訊', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '9.3.2', name: '建議之資訊', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '9.3.3', name: '選購資訊及相關連要求事項', docRef: '', status: ComplianceStatus.COMPLIANT },
  { id: '10', name: '組織在查驗活動中之角色', docRef: '', status: ComplianceStatus.COMPLIANT },
];

export const G3026_DEFAULT_CHECKLIST: ChecklistItem[] = [
  { id: '1.1', name: '確保組織採用界定組織之方法符合法規要求，以進行其排放量與移除量彙總方式：(1)營運控制權(2)股份持分', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '1.2', name: '確保組織已將組織邊界設定方法及排放量與移除量彙總方式予以文件化，並於溫室氣體報告中揭露組織邊界設定方法及排放量與移除量彙總方式。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '1.3', name: '確保組織採相同的方法彙總各排放設施之排放量，以避免發生重覆計算或遺漏。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '1.4', name: '確保組織邊界若有任何的變動及未納入盤查者，應清楚且合理說明原因。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '2.1', name: '確保組織所採用之報告邊界設定方法ISO 14064-1自願性方案訂定之相關規範，完整涵蓋類別1至類別6之排放。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '2.2', name: '確保已量化其組織邊界內之設施所產生的直接溫室氣體排放。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '2.3', name: '確保已量化其消耗的輸入電力、熱能或蒸氣所產生之間接溫室氣體排放。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '2.4', name: '適當時，確保生質燃燒產生之二氧化碳排放已分別量化。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '2.5', name: '確保組織所建立之溫室氣體排放量清冊，完整涵蓋組織邊界內所擁有或控制之溫室氣體排放設施，且正確設定各排放設施之報告邊界及其排放之溫室氣體種類。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '2.6', name: '確保營運邊界及其設定方法已文件化，完整地列出組織邊界內應負擔排放量與移除量之所有排放設施及溫室氣體種類之清單，且於溫室氣體報告揭露之。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '2.7', name: '確保組織採用一致的原則設定報告邊界，若有任何變動，應清楚且合理說明。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '3.1', name: '確保組織所採用之量化方法，符合相關規範，且為實務可行下最高準確等級之方式。若有例外情形，已清楚且合理說明原因。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '3.2', name: '確保組織完整量化組織邊界內溫室氣體：類別1-直接排放量、類別2-能源間接排放量、類別3-運輸間接排放量、類別4-原料/服務間接排放量、類別5-產品使用間接排放量源、類別6-其他來源間接排放量', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '3.3', name: '確保當發生免除量化或簡易量化溫室氣體排放時，組織已說明其理由。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '3.4', name: '確保組織已將排放設施之量化方法予以文件化，並運用一致的量化方法發展排放量清冊，以產生準確的、一致的及具再現性的結果。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '3.5', name: '確保組織使用適切的溫暖化潛勢(GWP) 將每種溫室氣體排放量轉換成二氧化碳當量公噸(CO2e)。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '4.1', name: '確保組織設定之基準年符合ISO14064-1自願性溫室氣體盤查方案之要求。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '4.2', name: '確保組織所選擇之基準年相關數據具有可查驗性。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '4.3', name: '確保組織已將基準年選擇的原因、調整政策、重新計算之原則與程序文件化，包括清楚說明啟動基準年排放量重新計算之顯著性門檻。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '4.4', name: '確保組織盤查年採用與基準年一致之組織與報告邊界設定及量化方法，包含活動數據與排放係數之選擇等，若有任何變動，應清楚且合理說明，適當時，重新計算基準年之溫室氣體排放量清冊。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.1', name: '確保組織所採用之數據品質管理程序符合相關要求及ISO 14064-1對排放量清冊品質管理之標準條文釋義。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.2', name: '確保組織已文件化並落實資料蒐集與處理過程之數據品質管理程序。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.3', name: '確保組織所建立之數據品質管理程序完整涵蓋盤查相關之環節且順利運作，以達到下列目的。(1)確認盤查採用之假設條件、量化方法與所引用相關數據的有效性與代表性。(2)確認盤查運算之正確性。(3)判斷排放量盤查結果之合理性。(4)有效鑑別數據品質與資訊管理系統之錯誤與不確定性來源，並評估其衝擊。(5)有效降低不確定性，以改善盤查結果之數據品質，達到持續改善的目標。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.4', name: '確保組織已文件化數據品質管理的執行結果及所發現問題的解決作法，並將相關結果傳達予相關單位，在實務可行下消除已發生之錯誤或減少發生錯誤之潛在風險來源。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
  { id: '5.5', name: '確保組織適當保存數據品質管理相關紀錄與文件。', docRef: '', fieldObs: '', status: ComplianceStatus.COMPLIANT },
];
